### ISSUE TITLE
Frontned javascript

### ISSUE THREAD

**Issue by Karyum** [WebAhead12/Whos-That-Pokemon#1]
A whole bunch of small fixes that can generally improve the code:

1) using a foreach [here](https://github.com/WebAhead12/Whos-That-Pokemon/blob/main/www/script.js#L46) instead of a for loop.
2) Meaningful names for variables [here](https://github.com/WebAhead12/Whos-That-Pokemon/blob/main/www/script.js#L47-L48)
3) Splitting the fetch to a function that takes the url
4) ## Handling errors
    https://github.com/WebAhead12/Whos-That-Pokemon/blob/main/www/script.js#L82
https://github.com/WebAhead12/Whos-That-Pokemon/blob/main/www/script.js#L91

**Comment by Iz1cK** [comment]
https://github.com/WebAhead12/Whos-That-Pokemon/blob/5c4e0f6983a5626d87927a7660ca205fbd84054b/www/script.js#L47-L49

https://github.com/WebAhead12/Whos-That-Pokemon/blob/5c4e0f6983a5626d87927a7660ca205fbd84054b/www/script.js#L58
