### ISSUE TITLE
Issue with one-type pokemon

### ISSUE THREAD

**Issue by Nur1995** [WebAhead12/Whos-That-Pokemon#2]
When you have a pokemon with one type, the user also sees an empty block next to it. However, when you search for a pokemon with two abilities, and you go back to the pokemon with one ability, you can see that it adopts the second pokemon's second type.

Try typing "Pikachu," you'll see the empty block next to "Electric." Afterwards, when you search for "Odish," you can see that the second type is "Poison," which is correct. However, when you go back and search "Pikachu," or any other pokemon with one type, you'll see that it adopts the "poison" type from "Odish"

**Comment by Iz1cK** [comment]
https://github.com/WebAhead12/Whos-That-Pokemon/blob/5c4e0f6983a5626d87927a7660ca205fbd84054b/www/script.js#L115-L120

https://github.com/WebAhead12/Whos-That-Pokemon/blob/5c4e0f6983a5626d87927a7660ca205fbd84054b/www/script.js#L75-L76
