### ISSUE TITLE
Issue with placeholder font-color

### ISSUE THREAD

**Issue by Nur1995** [WebAhead12/Whos-That-Pokemon#3]
The placeholder text is a little too light to see. Without zooming in, the user can see that there might be some text there,, but it's not too visible. We suggest making a the placeholder text a little darker, perhaps a dark grey.

**Comment by Iz1cK** [comment]
https://github.com/WebAhead12/Whos-That-Pokemon/blob/5c4e0f6983a5626d87927a7660ca205fbd84054b/www/style.css#L98

Made the color significantly darker
